### ISSUE TITLE
Screenshot for your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [vfilipovsky/password-tool#1]
Hi!  You've got something most Python programs don't..... a graphical user interface.  Visitors love seeing pictures.  It's easy to drop a screenshot of your program into your readme.  You can use GitHub Issues to do it if you want.  This image:

![image](https://user-images.githubusercontent.com/46163555/142059611-58661efa-ce31-4799-9fe3-f92da2b188e0.png)

can be put into your readme by adding this line to your readme.md file:

```
![image](https://user-images.githubusercontent.com/46163555/142059611-58661efa-ce31-4799-9fe3-f92da2b188e0.png)
```

Thanks for sharing what you made!

**Comment by vfilipovsky** [comment]
Hi! No problem, added!

**Comment by PySimpleGUI** [comment]
Nice!
